apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: demo
        image: 76591745/angularkubernetes
        ports:
        - containerPort: 80
